tap "1password/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "jandedobbeleer/oh-my-posh"
tap "mongodb/brew"
tap "ngrok/ngrok"
tap "pilotmoon/tap"
brew "bat"
brew "curl"
brew "deno"
brew "doctl"
brew "exa"
brew "freetds"
brew "gh"
brew "gitleaks"
brew "httpie"
brew "jq"
brew "lzfse"
brew "mas"
brew "node@16"
brew "mongosh"
brew "nodenv"
brew "tidy-html5"
brew "php"
brew "rbenv"
brew "wget"
brew "yt-dlp"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
brew "mongodb/brew/mongodb-database-tools"
cask "1password"
cask "1password-cli"
cask "alfred"
cask "aquaticprime"
cask "backblaze"
cask "bbedit"
cask "charles"
cask "dash"
cask "docker"
cask "dropbox"
cask "eaglefiler"
cask "find-any-file"
cask "firefox"
cask "gitup"
cask "google-chrome"
cask "google-cloud-sdk"
cask "hex-fiend"
cask "iina"
cask "imageoptim"
cask "insomnia"
cask "komet"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "mongodb-compass"
cask "netnewswire"
cask "ngrok"
cask "numi"
cask "obs"
cask "obsidian"
cask "popclip"
cask "private-internet-access"
cask "scroll-reverser"
cask "setapp"
cask "signal"
cask "sketch"
cask "skim"
cask "spotify"
cask "superduper"
cask "syntax-highlight"
cask "todoist"
cask "transmit"
cask "visual-studio-code"
cask "whatsapp"
mas "1Password for Safari", id: 1569813296
mas "Boop", id: 1518425043
mas "Broadcasts", id: 1469995354
mas "Grammarly for Safari", id: 1462114288
mas "Hyperfocus", id: 1621523525
mas "Integrity", id: 513610341
mas "Key Codes", id: 414568915
mas "MarkEdit", id: 1669953820
mas "Numbers", id: 409203825
mas "Onigiri", id: 1639917298
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "Table Tool", id: 1122008420
mas "Tot", id: 1491071483
mas "Track", id: 1191484642
mas "Velja", id: 1607635845
mas "Xcode", id: 497799835